### ISSUE TITLE
textLength

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#28]
I did not find any image with a-textLength in the test-suite, did I miss it/them?

relating issues:
* resvg: https://github.com/RazrFalcon/resvg/issues/204
* Wikimedia: https://phabricator.wikimedia.org/T15387

**Comment by RazrFalcon** [comment]
This tests suite contains mainly tests for features that are already implemented in resvg. `textLength` is not.
The problem is that before adding tests I should figure out what is the correct output first. And this is often non-trivial and time consuming.

And since this a text-related feature it's probably badly broken everywhere.

**Comment by RazrFalcon** [comment]
Done.
